// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxo9XwWgVMZadmBlAwQD4DI4dYamE5Ys8',
    appId: '1:66519056841:web:f15998d71c66a6be186818',
    messagingSenderId: '66519056841',
    projectId: 'restaurant-management-53e1c',
    authDomain: 'restaurant-management-53e1c.firebaseapp.com',
    storageBucket: 'restaurant-management-53e1c.appspot.com',
    measurementId: 'G-JSMHJGHPP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5TvdSj6t0kTLskTPjpYlhL3BNWUu7O3w',
    appId: '1:66519056841:android:42a590262dd19d1e186818',
    messagingSenderId: '66519056841',
    projectId: 'restaurant-management-53e1c',
    storageBucket: 'restaurant-management-53e1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iu_14d4Ip7T3TO5DqBhcn_SfTOp_-So',
    appId: '1:66519056841:ios:380420d56efa6d5c186818',
    messagingSenderId: '66519056841',
    projectId: 'restaurant-management-53e1c',
    storageBucket: 'restaurant-management-53e1c.appspot.com',
    iosClientId: '66519056841-uh4cia8kfehdkcileiarmbhkhoh6i5vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iu_14d4Ip7T3TO5DqBhcn_SfTOp_-So',
    appId: '1:66519056841:ios:380420d56efa6d5c186818',
    messagingSenderId: '66519056841',
    projectId: 'restaurant-management-53e1c',
    storageBucket: 'restaurant-management-53e1c.appspot.com',
    iosClientId: '66519056841-uh4cia8kfehdkcileiarmbhkhoh6i5vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantManagement',
  );
}
